version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - depguard
    - revive
    - nlreturn
    - ireturn
    - nonamedreturns
    - wrapcheck
    - staticcheck
    - gochecknoglobals
  exclusions:
    paths:
    - (.+)_test\.go
